### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ArmandoAmador** [ArmandoAmador/royalcremas#1]
Royal Cremas
- [x] Setup mailer
- [x] Create Form
- [x] Setup Sendgrid on heroku
- [ ] Sendgrid is slow, research what's being delayed
- [ ] Setup unicorn
- [x] Setup paypal
- [ ] Events page with gallery
- [ ] Active Admin for him to edit his own site
- [ ] Transfer heroku ownership to ralph
- [ ] Show him sendgrid
- [ ] Show him heroku
